### ISSUE TITLE
“Applies when” conditions are hard to read on mobile. 

### ISSUE THREAD

**Issue by gdoenlen** [davidmreed/paytransparency.work#13]
The conditions for when a state’s law applies is hard to read on mobile due to their lack of punctuation, capitalization, and bullets.  It’s really easy to get lost in them. On desktop they’re a single line due to the width of most desktops so it isn’t as noticeable. 

![C9A41EAA-598D-476D-8575-EF2267C8A3ED](https://user-images.githubusercontent.com/17297466/222146430-57bfe744-676f-4b70-8e3e-af9b40e59dec.jpeg)

**Comment by davidmreed** [comment]
I've added punctuation, which I hope makes this easier to read on mobile!
